"""initial_migration

Revision ID: 0d944a319cef
Revises: 
Create Date: 2026-05-19 16:50:31.571577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d944a319cef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_simulations_modele'), table_name='ai_simulations')
    op.drop_index(op.f('idx_ai_simulations_session_id'), table_name='ai_simulations')
    op.drop_index(op.f('ix_ai_simulations_session_id'), table_name='ai_simulations')
    op.drop_table('ai_simulations')
    op.drop_index(op.f('idx_exercises_difficulte'), table_name='exercises')
    op.drop_index(op.f('idx_exercises_domaine'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulte'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_domaine'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_titre'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('idx_users_actif'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_courriel'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_feedbacks_score_global'), table_name='feedbacks')
    op.drop_index(op.f('idx_feedbacks_session_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_session_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('idx_sessions_commence_le'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_exercice_id'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_statut'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_utilisateur_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_exercice_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_utilisateur_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('idx_progress_domaine'), table_name='progress')
    op.drop_index(op.f('idx_progress_utilisateur_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_utilisateur_id'), table_name='progress')
    op.drop_table('progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domaine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_sessions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_moyen', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('meilleur_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('serie', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('derniere_session_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], name=op.f('progress_utilisateur_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('progress_pkey'))
    )
    op.create_index(op.f('ix_progress_utilisateur_id'), 'progress', ['utilisateur_id'], unique=True)
    op.create_index(op.f('idx_progress_utilisateur_id'), 'progress', ['utilisateur_id'], unique=False)
    op.create_index(op.f('idx_progress_domaine'), 'progress', ['domaine'], unique=False)
    op.create_table('sessions',
    sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('commence_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('termine_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reponses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercises.id'], name=op.f('sessions_exercice_id_fkey')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], name=op.f('sessions_utilisateur_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('ix_sessions_utilisateur_id'), 'sessions', ['utilisateur_id'], unique=False)
    op.create_index(op.f('ix_sessions_exercice_id'), 'sessions', ['exercice_id'], unique=False)
    op.create_index(op.f('idx_sessions_utilisateur_id'), 'sessions', ['utilisateur_id'], unique=False)
    op.create_index(op.f('idx_sessions_statut'), 'sessions', ['statut'], unique=False)
    op.create_index(op.f('idx_sessions_exercice_id'), 'sessions', ['exercice_id'], unique=False)
    op.create_index(op.f('idx_sessions_commence_le'), 'sessions', ['commence_le'], unique=False)
    op.create_table('feedbacks',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score_global', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('points_forts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ameliorations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommandations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('genere_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('feedbacks_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedbacks_pkey'))
    )
    op.create_index(op.f('ix_feedbacks_session_id'), 'feedbacks', ['session_id'], unique=True)
    op.create_index(op.f('idx_feedbacks_session_id'), 'feedbacks', ['session_id'], unique=False)
    op.create_index(op.f('idx_feedbacks_score_global'), 'feedbacks', ['score_global'], unique=False)
    op.create_table('users',
    sa.Column('courriel', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mot_de_passe_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('domaine', postgresql.ENUM('TECHNIQUE', 'COMPORTEMENTAL', 'SITUATIONNEL', 'ETUDE_DE_CAS', 'MOTIVATION', name='domaine'), autoincrement=False, nullable=True),
    sa.Column('niveau', postgresql.ENUM('DEBUTANT', 'INTERMEDIAIRE', 'AVANCE', 'EXPERT', name='niveau'), autoincrement=False, nullable=True),
    sa.Column('est_actif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_courriel'), 'users', ['courriel'], unique=True)
    op.create_index(op.f('idx_users_email'), 'users', ['courriel'], unique=False)
    op.create_index(op.f('idx_users_actif'), 'users', ['est_actif'], unique=False)
    op.create_table('exercises',
    sa.Column('titre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('domaine', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulte', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duree_sec', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('etiquettes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('difficulte_estimee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.create_index(op.f('ix_exercises_titre'), 'exercises', ['titre'], unique=False)
    op.create_index(op.f('ix_exercises_domaine'), 'exercises', ['domaine'], unique=False)
    op.create_index(op.f('ix_exercises_difficulte'), 'exercises', ['difficulte'], unique=False)
    op.create_index(op.f('idx_exercises_domaine'), 'exercises', ['domaine'], unique=False)
    op.create_index(op.f('idx_exercises_difficulte'), 'exercises', ['difficulte'], unique=False)
    op.create_table('ai_simulations',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('modele', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jetons_prompt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jetons_reponse', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('ai_simulations_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_simulations_pkey'))
    )
    op.create_index(op.f('ix_ai_simulations_session_id'), 'ai_simulations', ['session_id'], unique=True)
    op.create_index(op.f('idx_ai_simulations_session_id'), 'ai_simulations', ['session_id'], unique=False)
    op.create_index(op.f('idx_ai_simulations_modele'), 'ai_simulations', ['modele'], unique=False)
    # ### end Alembic commands ###
